USE case_study_web_game;
insert into game_item(item_image, item_int, item_mind, item_name, item_price, item_special, item_str, item_vit)
values ('../img/item/aegis-of-the-legion-item.webp', 3, 6, 'khiên', 500, 'khiên', 6, 5),
       ('../img/item/randui27s-omen-item.webp', 4, 5, 'khiên II', 500, 'khiên II', 6, 5),
       ('../img/item/aether-wisp-item.webp', 6, 4, 'nước thánh', 500, 'nước thánh', 5, 5),
       ('../img/item/bandleglass-mirror-item.webp', 3, 5, 'gương thần', 500, 'gương thần', 4, 4),
       ('../img/item/bami27s-cinder-item.webp', 4, 5, 'lửa thần', 500, 'lửa thần', 6, 5),
       ('../img/item/serrated-dirk-item.webp', 6, 4, 'phi tiêu', 500, 'phi tiêu', 5, 5),
       ('../img/item/pickaxe-item.webp',5,7,'mỏ',500,'mỏ',4,4),
       ('../img/item/noonquiver-item.webp', 5, 6, 'cung tên', 500, 'cung  tên', 3, 8),
       ('../img/item/warden27s-mail-item.webp', 3, 6, 'áo giáp', 500, 'áo giáp', 5, 6),
       ('../img/item/chain-vest-item.webp', 5, 6, 'áo giáp vảy rồng', 500, 'áo giáp vảy rồng', 3, 6),
       ('../img/item/negatron-cloak-tem.webp', 5, 6, 'áo choàng', 500, 'áo choàng', 7, 2),
       ('../img/item/bramble-vest-item.webp', 4, 7, 'áo kỵ sỹ', 500, 'áo kỵ sĩ', 5, 4),
       ('../img/item/crystalline-bracer-item.webp', 8, 3, 'găng tayII', 500, 'găng tayII', 3, 6),
       ('../img/item/iceborn-gauntlet-item.webp', 6, 5, 'găng tay', 500, 'găng tay', 3, 6),
       ('../img/item/brawler27s-gloves-item.webp', 6, 7, 'găng tay quái thú', 500, 'găng tay quái thú', 6, 1),
       ('../img/item/gusto-item.webp', 5, 6, 'cú đấm của phù thủy', 500, 'cú đấm của phù thủy    ', 5, 4),
       ('../img/item/pauldrons-of-whiterock-item.webp', 4, 5, 'Mũ vàng', 500, 'Mũ vàng', 6, 5),
       ('../img/item/demonic-embrace-item.webp', 6, 7, 'Mũ sunmuray', 500, 'Mũ sunmuray', 4, 3),
       ('../img/item/wooglet27s-witchcap-item.webp', 4, 7, 'mũ phù thủy', 500, 'mũ phù thủy', 5, 4),
       ('../img/item/knight27s-vow-item.webp', 5, 6, 'mũ kỵ sĩ', 500, 'mũ kỵ sĩ', 3, 9),
       ('../img/item/caulfield27s-warhammer-item.webp', 4, 6, 'búa thần', 500, 'búa thần', 3, 7),
       ('../img/item/phage-item.webp', 4, 5, 'búa vàng', 500, 'bùa vàng', 3, 8),
       ('../img/item/giant27s-belt-item.webp', 6, 3, 'thắp lưng', 500, 'thắp lưng', 7, 4),
       ('../img/item/tiamat-item.webp', 6, 3, 'rìu vàng', 500, 'rìu vàng', 2, 9),
       ('../img/item/vampiric-scepter-item.webp',4,5,'lưới hái tử thần',500,'lưới hái tử thần',4,7),
       ('../img/item/winged-moonplate-item.webp', 5, 7, 'váy', 500, 'váy', 4, 4),
       ('../img/item/infinity-edge-item.webp', 6, 4, 'kiếm vàng', 500, 'kiếm vàng', 5, 5),
       ('../img/item/bloodthirster-item.webp', 7, 5, 'kiếm pháp sư', 500, 'kiếm pháp sư', 4, 4),
       ('../img/item/muramana-item.webp', 6, 3,'thần kiếm',500,'thần kiếm',5,6),
       ('../img/item/navori-quickblades-item.webp',5,7,'ba kiếm',500,'ba kiếm',4,4),
       ('../img/item/wit27s-end-item.webp',4,8,'kiếmI',500,'kiếmI',5,7),
       ('../img/item/void-staff-item.webp',6,5,'gậy phù thủy',500,'gây phù thủy',5,4),
       ('../img/item/lich-bane-item.webp',6,7,'long đao',500,'long đao',5,2),
       ('../img/item/zeal-item.webp',5,6,'song đao',500,'song đao',4,5),
       ('../img/item/Ironspike-whip-item.webp',6,7,'xích sắt',500,'xích sắt',5,2),
       ('../img/item/liandry27s-torment-item.webp',6,7,'mặt nạ tử thần',500,'mặt nạ tử thần',1,6),
       ('../img/item/luden27s-tempest-item.webp',5,6,'kiếm của Công',500,'kiếm của công',3,6),
       ('../img/item/mikael27s-blessing-item.webp',5,6,'chuông vàng',500,'chuông vàng',5,4),
       ('../img/item/berserker27s-greaves-item.webp',5,7,'giày kỵ sỹ',500,'giày kỵ sỹ',4,4),
       ('../img/item/boots-of-swiftness-item.webp',7,6,'giày tuyết',500,'giày tuyết',3,4),
       ('../img/item/mobility-boots-item.webp',6,7,'giày lửa',500,'giày lửa',5,2),
       ('../img/item/sorcerer27s-shoes-item.webp',4,7,'giày thần',500,'giày thần',5,4),
       ('../img/item/serpent27s-fang-item.webp',4,7,'kiếm bậc II',500,'kiếm bậc II',4,5)